Friendship v1
JelilFaisalAbudu/ror-social-scaffold pull request #4
Opened 2020-09-11 17:16 UTC by JelilFaisalAbudu

# Requesting code review for the ror-social-scaffold project

* I have completed the version one of the friendship features of the project. It's therefore ready for your review.

## Features of this version

* The user can sent friend requests to other users
* The user accept or decline a friend request
* The user can delete the existing friendship between other users
* The cannot befriend himself or befriend others more than once

## RSpec

* I've performed association and validation test for friendship model
* I've also performed integration test for friendships features

### Thanks...

2020-09-11 21:48 UTC, wathigo requested changes
### Changes Required.
Great job on this project. Let's make some changes in order to meet all the requirements.

**REQUIRED**
* Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, I can be able to view other users posts even if we are not friends.


**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

2020-09-11 21:48 UTC, wathigo commented on app/views/users/show.html.erb
> +
**REQUIRED**
There is a button to invite the user to friendship on the users list page and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from Pathwright).
Let's add a button to add friendship in `users#show`.

2020-09-12 20:01 UTC, JelilFaisalAbudu commented
# Changes to the code ready for another review

* Friend request button added to the user show page
* Timeline modified to include only the user and his friends

2020-09-12 21:39 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @JelilFaisalAbudu :balloon: 

### Thank you for doing the changes requested by the previous reviewer :1st_place_medal: your project is working great and you have a good amount of unit and integration test cases for it so claps to you for that :clap: :clap: :clap: awesome work indeed :sparkles: I only have one request regarding coding good practices so let's address it before we move on, shall we? :construction: :construction_worker: 

#### No Logic or complexity in Views or Partials

* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources** [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
[screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- I've left comments in the views where I found complexity (if, if/else, unless and /or ternary operators) please create helper methods to handle this instead of doing it straight in the views or partials.

- [OPTIONAL] The scaffolded project came with logic and complexity? let's fix it too! :muscle: 

### That's it :raised_hands: 

### Please :pray: do the changes :technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-09-12 21:39 UTC, euqueme commented on app/views/users/show.html.erb
> +	<% end %>
- [ ] put the contents of this `unless` statement in a `partial` and the `unless` statement within a `helper method` that renders the `partial` when the condition is met, and call the `helper method` here instead of the `unless` statement

- [ ] Do the same fo the `if` statement within the `each block` so you don't have complexity within the `partial`

2020-09-12 21:39 UTC, euqueme commented on app/views/users/show.html.erb
> +	<% end %>
- [ ] put the contents of this `unless` statement in a `partial` and the `unless` statement within a `helper method` that renders the `partial` when the condition is met, and call the `helper method` here instead of the `unless` statement

- [ ] Do the same fo the `if` statement within the `each block` so you don't have complexity in the `partial`

2020-09-13 21:12 UTC, JelilFaisalAbudu commented
# Requesting code Review for current changes made

* All the logics in the view templates have been moved to helper methods. I'm submitting it for your review

## Thanks...

2020-09-14 00:40 UTC, MarioDena approved these changes
Well done implementing the requested changes.

Project Approved.  🎖️

2020-09-14 10:03 UTC, merged